# ***CHAPTER 1 :- PANDAS***


---

#***1)WHAT IS PANDAS  ?***

PANDAS IS A POWERFUL PYTHON LIBRARY USED FOR DATA ANALYSIS, DATA MANIPULATION, AND DATA CLEANING.
IT PROVIDES EASY-TO-USE DATA STRUCTURES AND TOOLS TO WORK WITH LABELED OR TABULAR DATA (LIKE EXCEL SHEETS OR DATABASE TABLES).


---



**MEANING:**

THE WORD “PANDAS” COMES FROM “PYTHON DATA ANALYSIS LIBRARY.”

IT IS BUILT ON TOP OF NUMPY, WHICH MAKES IT VERY FAST AND EFFICIENT.



---


**MAIN FEATURES OF PANDAS:**

EASY DATA CLEANING AND HANDLING.

SUPPORTS IMPORTING DATA FROM CSV, EXCEL, SQL, JSON, ETC.

POWERFUL OPERATIONS LIKE FILTERING, GROUPING, SORTING, AND MERGING.

BUILT ON TOP OF NUMPY, MAKING IT FAST AND EFFICIENT.

IDEAL FOR DATA SCIENCE AND MACHINE LEARNING PROJECTS.


---

# ***2)WHY WE HAVE TO IMPORT NUMPY BEFORE PANDAS ?***
WE IMPORT NUMPY FIRST BECAUSE PANDAS IS BUILT ON TOP OF NUMPY.
NUMPY PROVIDES THE CORE DATA STRUCTURE (ARRAYS) THAT PANDAS USES INTERNALLY TO STORE AND MANAGE DATA.


---

# DETAILED EXPLANATION:-

PANDAS DEPENDS ON NUMPY

PANDAS USES NUMPY ARRAYS UNDERNEATH ITS OWN DATA STRUCTURES (LIKE SERIES AND DATAFRAME).

ALL NUMERICAL OPERATIONS INSIDE PANDAS (LIKE MEAN, SUM, SORT, ETC.) USE NUMPY FUNCTIONS.

# `SO, WITHOUT NUMPY, PANDAS CANNOT WORK PROPERLY`.


---
NUMPY HANDLES MATHEMATICAL OPERATIONS

PANDAS IS DESIGNED FOR DATA ANALYSIS, NOT FOR LOW-LEVEL MATH OPERATIONS.

NUMPY PROVIDES THOSE MATHEMATICAL AND ARRAY FUNCTIONS (LIKE np.sum(), np.mean(), np.array()), WHICH PANDAS USES INTERNALLY.

DATA STRUCTURE CONNECTION

A PANDAS SERIES IS BASICALLY A WRAPPER AROUND A NUMPY ARRAY WITH ADDED LABELS (INDEX).

A PANDAS DATAFRAME IS A COLLECTION OF MULTIPLE SERIES OBJECTS THAT ALL USE NUMPY ARRAYS UNDER THE HOOD.

---
PANDAS IMPORTS NUMPY AUTOMATICALLY

WHEN YOU import pandas, IT INTERNALLY IMPORTS NUMPY TOO.

BUT, SOMETIMES DEVELOPERS IMPORT NUMPY FIRST TO USE BOTH TOGETHER FOR ADVANCED CALCULATIONS.

---
#  `CONCLUSION:-`

WE IMPORT NUMPY BEFORE PANDAS BECAUSE
PANDAS USES NUMPY’S FUNCTIONS, ARRAYS, AND OPERATIONS INTERNALLY TO WORK WITH DATA EFFICIENTLY.

#***TOPIC 1 :- SERIES***


---

## 3)WHAT IS SERIES ?
 SERIES IS A ONE DIMENSIONAL  LABEL ARRAY THAT  IS CAPABLE FOR HANDALING DATA OF ANY LABEL

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

# ***4)WHY WE IMPORT WARNINGS IN PYTHON***

WARNINGS text IS A BUILT-IN PYTHON MODULE THAT IS USED TO CONTROL, IGNORE, OR MANAGE WARNING MESSAGES THAT APPEAR WHEN A PROGRAM RUNS.

SOMETIMES, WHEN YOU RUN CODE, PYTHON SHOWS WARNINGS (NOT ERRORS) — THESE WARNINGS DO NOT STOP THE PROGRAM, BUT THEY CAN MAKE THE OUTPUT LOOK MESSY OR CONFUSING.

TO HANDLE THIS, WE IMPORT THE WARNINGS MODULE.

---

# WHY WE USE IT ?

🛑 TO HIDE UNNECESSARY WARNING MESSAGES

SOMETIMES, LIBRARIES LIKE NUMPY, PANDAS, OR SCIKIT-LEARN SHOW WARNINGS ABOUT SMALL ISSUES (E.G., DEPRECATED FUNCTIONS).

THESE WARNINGS DO NOT AFFECT THE CODE RESULT, BUT THEY MAKE THE OUTPUT LOOK CLUTTERED.

**TO STOP THEM, WE USE:**


# **`warnings.filterwarnings('ignore')`**


---
**WARNINGS MODULE IS USED TO MANAGE, IGNORE, OR DISPLAY WARNING MESSAGES IN PYTHON PROGRAMS.**

In [ ]:
import warnings

In [ ]:
warnings.filterwarnings("ignore")

In [ ]:
a=pd.Series()

In [ ]:
print(a)

Series([], dtype: object)

In [ ]:
a=pd.Series(data=[1,2,3],index=['a','b','c'])

In [ ]:
a

a    1
b    2
c    3
dtype: int64

In [ ]:
x={"a":1,"b":2,"c":3}

In [ ]:
a=pd.Series(x)

In [ ]:
a

a    1
b    2
c    3
dtype: int64

In [ ]:
a=pd.Series(data=[1,2,3],index=['a','b','c','d'])

ValueError: Length of values (3) does not match length of index (4)

In [ ]:
x={"a":1,"b":2,"c":3}
a=pd.Series(data=x,index=['a','b','c','d'],dtype=int)

In [ ]:
a

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [ ]:
i=np.array(["a","b","c"])
d=np.array([1,2,3])
a=pd.Series(data=i,index=d)
a

1    a
2    b
3    c
dtype: object

In [ ]:
l=np.arange(1,11)
k=np.array(["a1","a2","a3","a4","a5","a6","a7","a8","a9","a10"])
h=pd.Series(data=l,index=k)
h

a1      1
a2      2
a3      3
a4      4
a5      5
a6      6
a7      7
a8      8
a9      9
a10    10
dtype: int64

In [ ]:
t=pd.Series(data=5,index=[1,2,3,4,5,6])

In [ ]:
t

1    5
2    5
3    5
4    5
5    5
6    5
dtype: int64

# ***TOPIC 2 :- DATA FRAME***


---


#1)WHAT IS DATA FRAME ?
 DATA FRAME IS TWO DIMENSIONAL DATA STRUCTURE EITHER DATA IS ALING IN TABULAR FORMAT WHICH IS ROW AND COLUMN

In [ ]:
d=pd.DataFrame()

In [ ]:
d

Empty DataFrame
Columns: []
Index: []

In [ ]:
print(d)

Empty DataFrame
Columns: []
Index: []

In [ ]:
d=pd.DataFrame([1,2,3,4,5])

In [ ]:
d

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
d=pd.DataFrame([1,2,3,4,5],columns=["Srno"])

In [ ]:
d

   Srno
0     1
1     2
2     3
3     4
4     5

from matplotlib import pyplot as plt
d['Srno'].plot(kind='hist', bins=20, title='Srno')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Srno']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Srno'}, axis=1)
              .sort_values('Srno', ascending=True))
  xs = counted['Srno']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = d.sort_values('Srno', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Srno')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
d['Srno'].plot(kind='line', figsize=(8, 4), title='Srno')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
name=['pratik','purvesh','faizan','sandesh','madhu','vinayak']
py=[89,78,75,64,45,25]
ml=[89,57,65,78,25,35]
dic={'NAME':name,'PYTHON':py,'ML':ml}

In [ ]:
a=pd.DataFrame(dic)

In [ ]:
a

      NAME  PYTHON  ML
0   pratik      89  89
1  purvesh      78  57
2   faizan      75  65
3  sandesh      64  78
4    madhu      45  25
5  vinayak      25  35

from matplotlib import pyplot as plt
a['PYTHON'].plot(kind='hist', bins=20, title='PYTHON')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
a['ML'].plot(kind='hist', bins=20, title='ML')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
a.groupby('NAME').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
a.plot(kind='scatter', x='PYTHON', y='ML', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
a['PYTHON'].plot(kind='line', figsize=(8, 4), title='PYTHON')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
a['ML'].plot(kind='line', figsize=(8, 4), title='ML')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(a['NAME'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(a, x='PYTHON', y='NAME', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(a['NAME'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(a, x='ML', y='NAME', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)